language: ruby
rvm:
  - '2.7'

before_script:
  - chmod +x ./pages/script/cibuild

script: ./pages/script/cibuild

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler
notifications:
  email: false