language: node_js
node_js:
  - '14'

branches:
  only:
    - master

cache:
  yarn: true

script:
  - git config --global user.name "${GH_USERNAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd pages && yarn && GIT_USER="${GH_USERNAME}" yarn deploy


notifications:
  email: false