language: ruby
rvm:
  - '2.7'

before_script:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler
notifications:
  email: false