language: ruby
rvm:
  - '2.7'

before_script:
  - chmod +x jekyll.sh
  - bundle install

script: ./jekyll.sh

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler
notifications:
  email: false